name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    env:
      HOME: /root
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    defaults:
      run:
        working-directory: VINScanner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies (clean install)
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: VINScanner/playwright-report
          retention-days: 30